# Site info
title:               Orzapp
tagline:             Another website
url:                 http://data.orzapp.com
baseurl:             ""


#Config
highlighter: rouge
permalink: pretty
paginate: 4

#Analytics
google_analytics: UA-33617144-2

#Navigation
navs:
  -
    href: /
    label: index
  -
    href: /categories/
    label: category



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
