# Permalinks
permalink:           pretty

# Setup
title:               Orzapp
tagline:             Another website
url:                 http://data.orzapp.com
paginate:            1
baseurl:             ""

google_analytics: "UA-33617144-2"
theme: jekyll-theme-cayman

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
