# Permalinks
permalink:           pretty

# Setup
title:               Orzapp
tagline:             Another website
url:                 http://data.orzapp.com
paginate:            1
baseurl:             ""

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
